### ISSUE TITLE
Exception: BIND first!

### ISSUE THREAD

**Issue by Pescad0res** [CobblePot59/ADcheck#13]
`Traceback (most recent call last):
  File "/root/.local/bin/adcheck", line 8, in <module>
    sys.exit(run_main())
             ^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/adcheck/lib/python3.11/site-packages/adcheck/app.py", line 135, in run_main
    asyncio.run(main())
  File "/root/.pyenv/versions/3.11.10/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.10/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.10/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/adcheck/lib/python3.11/site-packages/adcheck/app.py", line 108, in main
    domain_sid = (await ad_client.get_ad_info())[0].objectSid
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/adcheck/lib/python3.11/site-packages/adcheck/libs/msldap/client.py", line 494, in get_ad_info
    async for entry, err in self.pagedsearch(ldap_filter, MSADInfo_ATTRS):
  File "/root/.local/share/pipx/venvs/adcheck/lib/python3.11/site-packages/adcheck/libs/msldap/client.py", line 179, in pagedsearch
    raise Exception('BIND first!')
Exception: BIND first!
`

**Comment by Pescad0res** [comment]
File "/root/.local/share/pipx/venvs/adcheck/lib/python3.11/site-packages/adcheck/app.py", line 123, in main
    await adcheck.connect()
  File "/root/.local/share/pipx/venvs/adcheck/lib/python3.11/site-packages/adcheck/core/__main__.py", line 38, in connect
    await self.update_entries()
  File "/root/.local/share/pipx/venvs/adcheck/lib/python3.11/site-packages/adcheck/core/__main__.py", line 62, in update_entries
    self.root_entry = [domain for domain in (await self.ad_client.get_ADobjects(custom_filter='(objectClass=domain)')) if domain.get('distinguishedName') == self.base_dn][0]
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
**IndexError: list index out of range**

**Comment by CobblePot59** [comment]
I recently updated the application, but it’s strange because this line is supposed to retrieve the domain root. Could you please test it with the latest update?
